### PR TITLE
area kmr

### PR DESCRIPTION
**Pull request by HailSanta**

### CODE REVIEW

**Comment by BowserSlug** [comment]
🚀 This PR matches 1 function (+0.00%) on `us`.

**Review by nanaian — CHANGES_REQUESTED** [review]
Happy new year 🥳

**Comment by nanaian** [comment]
Could you take a look at the added warnings before merging? @BowserSlug is saying this adds 620

**Comment by HailSanta** [comment]
> Could you take a look at the added warnings before merging? @BowserSlug is saying this adds 620

Fixed.

**Pull request merged**
