### PR TITLE
Update install_deps.sh

### PR DESCRIPTION
**Pull request by matejsmycka**

### CODE REVIEW

**Comment by ethteck** [comment]
I appreciate the intent behind this pr, but I don't think we should be automatically running pip install with the break system packages flag.

We have an open issue to rewrite this into a document that can be followed and doesn't have people mindlessly running `sudo some script.sh`. I think it'd be great to turn this into that document so we can explain things like why you might need to run pip install with this flag and what that means.

**Comment by matejsmycka** [comment]
I understand. While this initiative is great, users should be able to follow the guide or run a random script; taking responsibility for the script, the user should decide which approach he prefers.

About pip.

 You are inherently breaking system dependencies using pip. Either you are using a proper virtual environment or want it to "just work".  The current approach is halfway. My approach is to "just work". Maybe a better way would be to warn the user if command `x` doesn't work, use `--break-dependencies`. Or add poetry or pyenv....

**Comment by Darxoon** [comment]
If we are forcing everyone who wants to use the decomp to run a random shell script then we should really make sure it doesn't break people's systems. There's a reason `break-system-packages` is called the way it is

**Comment by matejsmycka** [comment]
Yes, but the current state still breaks them.

**Comment by Darxoon** [comment]
No? You will need to setup a venv before running install_deps.sh but it won't be able to harm the stability of your linux installation in general like `break-system-packages` has the potential to.

Remember that install_deps.sh is ran by a lot of people locally on their machines and using this flag carelessly like in your PR will inevitably make someone have to reinstall their OS because this flag *has* the potential to brick your entire linux installation if you're unfortunate.

**Comment by matejsmycka** [comment]
This is implicit info afaik

**Comment by bates64** [comment]
See #1059

**Pull request closed without merging**
