### PR TITLE
image fx

### PR DESCRIPTION
**Pull request by HailSanta**

### CODE REVIEW

**Review by nanaian — COMMENTED** [review]
Regarding capitalisation, you've gone for "Img**fx**" as if its one word but we have the following precedent

- AuFX
- AuFxBus

...looks like we need to pick something consistent; I'd prefer capital F and lowercase x personally (ImgFx) but up for discussion

**Comment by ethteck** [comment]
it depends on the context I think, unfortunately.

I think I prefer imgFX / ImgFX to imgFx / ImgFx

**Comment by BowserSlug** [comment]
🚀 This PR matches 1 function (+0.06%) on `us`.

🚀 This PR matches 1 function (+0.06%) on `ique`.

**Comment by nanaian** [comment]
@ethteck fine with me. I think im just against 'imgfx' as one word as it is in this PR

**Pull request merged**
