### PR TITLE
replaced commented out with if-0s

### PR DESCRIPTION
**Pull request by Alto1772**
Hey, long time no see! It's been long since a few months. Do you guys need this one? It only applies to existing functions that are failed to match and commented out by handmade workers.

### CODE REVIEW

**Comment by JoshDuMan** [comment]
I think this would be better if it instead did #ifdef NON_EQUIVALENT, rather than #if 0. Other than that, of course its appreciated!
=

**Comment by Brotenko** [comment]
I remember @ethteck saying that he personally wants most of these commented out functions to be completely removed (I think this was regarding map files only though?)

Personally speaking though, I agree with @JoshDuMan here that they should use `NON_MATCHING` and `NON_EQUIVALENT` though. Almost all the commented out funcs in the map files are equivalent though and only need data migration to match, so it'd be `NON_MATCHING` there and `NON_EQUIVALENT` when a function doesn't actually match the ASM.

**Comment by ethteck** [comment]
Hey, thanks for this! Yeah, I agree with comments above but all the map ones should be just straight-up deleted if you don't mind doing that

**Review by ethteck — CHANGES_REQUESTED** [review]
left my feedback in the last comment - oopz

**Comment by Alto1772** [comment]
wait why is this isnt merged?

**Comment by JoshDuMan** [comment]
> wait, why this isnt merged _yet_?

PRs require reviews from both Ethan and Alex typically. Alex hasn't taken a look yet.

**Comment by JoshDuMan** [comment]
From Ethan- "Ethan — Today at 3:27 AM
It wasn't merged because it's still waiting on the feedback to be addressed"

**Comment by ethteck** [comment]
To summarize: 
* All commented-out code in maps should be deleted entirely
* All other commented-out code should be `#ifdef NON_EQUIVALENT` (not `#ifdef 0 // NON_EQUIVALENT`)

**Comment by Brotenko** [comment]
> To summarize: 
> * All commented-out code in maps should be deleted entirely
> * All other commented-out code should be `#ifdef NON_EQUIVALENT` (not `#ifdef 0 // NON_EQUIVALENT`)

Unless it is actually equivalent but can't be matched due to, for example, missing data migration. Then it should be `NON_MATCHING`

**Review by ethteck — APPROVED** [review]
Thank you :) looks great.

**Review by nanaian — COMMENTED** [review]
The funcs that were added as NON_MATCHING should probably be marked NON_EQUIVALENT as per #534

**Comment by ethteck** [comment]
Oh yeah, oops. that was the intention. After that's done, I approve

**Review by nanaian — APPROVED** [review]

**Pull request merged**
