### PR TITLE
GCC 2.7.2 support

### PR DESCRIPTION
**Pull request by ethteck**
This removes the need for the kmc_gcc wrapper. Some issues remain, so I'm opening this so we can work on it together.

Also, most of an effect 😁

### CODE REVIEW

**Comment by BowserSlug** [comment]
⚠️ This PR introduces 59 warnings:
- src/18F340.c:345: warning: assignment from incompatible pointer type
- src/18F340.c:350: warning: assignment from incompatible pointer type
- src/18F340.c:364: warning: assignment from incompatible pointer type
- src/18F340.c:373: warning: assignment from incompatible pointer type
- src/1a1f0_len_5390.c:140: warning: assignment from incompatible pointer type
- src/1a1f0_len_5390.c:145: warning: assignment from incompatible pointer type
- src/1a1f0_len_5390.c:159: warning: assignment from incompatible pointer type
- src/1a1f0_len_5390.c:168: warning: assignment from incompatible pointer type
- src/battle/partner/watt.c:129: warning: assignment from incompatible pointer type
- src/battle/partner/watt.c:90: warning: assignment from incompatible pointer type
- src/effects/balloon.c:34: warning: assignment from incompatible pointer type
- src/effects/balloon.c:89: warning: initialization from incompatible pointer type
- src/effects/big_smoke_puff.c:123: warning: initialization from incompatible pointer type
- src/effects/big_smoke_puff.c:48: warning: assignment from incompatible pointer type
- src/effects/big_smoke_puff.c:77: warning: initialization from incompatible pointer type
- src/effects/cloud_puff.c:117: warning: initialization from incompatible pointer type
- src/effects/cloud_puff.c:30: warning: assignment from incompatible pointer type
- src/effects/cloud_trail.c:118: warning: initialization from incompatible pointer type
- src/effects/cloud_trail.c:29: warning: assignment from incompatible pointer type
- src/effects/effect_3C.c:18: warning: initialization from incompatible pointer type
- src/effects/effect_75.c:25: warning: initialization from incompatible pointer type
- src/effects/effect_86.c:112: warning: initialization from incompatible pointer type
- src/effects/effect_86.c:48: warning: assignment from incompatible pointer type
- src/effects/effect_86.c:79: warning: initialization from incompatible pointer type
- src/effects/emote.c:118: warning: initialization from incompatible pointer type
- src/effects/emote.c:77: warning: assignment from incompatible pointer type
- src/effects/ending_decals.c:18: warning: initialization from incompatible pointer type
- src/effects/energy_orb_wave.c:18: warning: initialization from incompatible pointer type
- src/effects/fire_breath.c:19: warning: initialization from incompatible pointer type
- src/effects/flame.c:27: warning: initialization from incompatible pointer type
- src/effects/floating_flower.c:146: warning: initialization from incompatible pointer type
- src/effects/floating_flower.c:29: warning: assignment from incompatible pointer type
- src/effects/floating_flower.c:79: warning: initialization from incompatible pointer type
- src/effects/floating_rock.c:19: warning: initialization from incompatible pointer type
- src/effects/flower_splash.c:142: warning: initialization from incompatible pointer type
- src/effects/flower_splash.c:65: warning: assignment from incompatible pointer type
- src/effects/flower_trail.c:160: warning: initialization from incompatible pointer type
- src/effects/flower_trail.c:67: warning: assignment from incompatible pointer type
- src/effects/footprint.c:119: warning: initialization from incompatible pointer type
- src/effects/footprint.c:41: warning: assignment from incompatible pointer type
- src/effects/landing_dust.c:108: warning: assignment from incompatible pointer type
- src/effects/landing_dust.c:216: warning: initialization from incompatible pointer type
- src/effects/landing_dust.c:261: warning: initialization from incompatible pointer type
- src/effects/lightning_bolt.c:29: warning: initialization from incompatible pointer type
- src/effects/small_gold_sparkle.c:113: warning: initialization from incompatible pointer type
- src/effects/small_gold_sparkle.c:45: warning: assignment from incompatible pointer type
- src/effects/snowflake.c:123: warning: initialization from incompatible pointer type
- src/effects/snowflake.c:30: warning: assignment from incompatible pointer type
- src/effects/snowflake.c:61: warning: initialization from incompatible pointer type
- src/effects/snowflake.c:86: warning: initialization from incompatible pointer type
- src/effects/star.c:120: warning: initialization from incompatible pointer type
- src/effects/star.c:182: warning: initialization from incompatible pointer type
- src/effects/star.c:43: warning: assignment from incompatible pointer type
- src/effects/walking_dust.c:39: warning: assignment from incompatible pointer type
- src/effects/walking_dust.c:97: warning: initialization from incompatible pointer type
- src/npc.c:1051: warning: assignment from incompatible pointer type
- src/npc.c:1071: warning: assignment from incompatible pointer type
- src/npc.c:1094: warning: assignment from incompatible pointer type
- src/npc.c:999: warning: assignment from incompatible pointer type

**Comment by BowserSlug** [comment]
🚀🚀🚀 This PR matches 3 functions (+0.03%) on `us`.

**Comment by JoshDuMan** [comment]
Might be worth removing the ifdefs for the files that had KMC support before? If you prefer not in this PR, that's understandable.

**Comment by ethteck** [comment]
yeah I'm planning on doing that next 🥂

**Review by nanaian — APPROVED** [review]
🆗 :)

**Pull request merged**
