### PR TITLE
Matched a bunch of duplicate functions in world/area

### PR DESCRIPTION
**Pull request by Nasina7**
Sorry that this PR is so big, this one function had around 50 unmatched duplicates :P

### CODE REVIEW

**Comment by BowserSlug** [comment]
🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀 This PR matches 52 functions (+0.22%) on `us`.

**Comment by ethteck** [comment]
https://discord.com/channels/279322074412089344/704241951972524063/1016571179542249512

**Review by nanaian — COMMENTED** [review]
These should probably be turned into an include

**Comment by ethteck** [comment]
> These should probably be turned into an include

yeah, they are already. we've discussed in diccord what to do about them

**Comment by ethteck** [comment]
Closing for now as per discussion in diccord

**Pull request closed without merging**
